apiVersion: v1
kind: Pod
metadata:
  labels:
    app: beehive
  name: beehive
spec:
  containers:
    # Create the first container: Dummy identd server on 113/TCP
    - name: beehive-server
      image: docker.io/fribbledom/beehive:latest
      env:
        - name: UID
          value: 1000
        - name: GID
          value: 1000
        - name: GIDLIST
          value: 1000
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: LANG
          value: en_US.UTF-8
        - name: HOME
          value: /tmp
        - name: AMDGPU_IDS
          value: /share/libdrm/amdgpu.ids
        - name: FONTCONFIG_PATH
          value: /etc/fonts
        - name: LD_LIBRARY_PATH
          value: /lib:/system
        - name: LIBVA_DRIVERS_PATH
          value: /lib/dri
        - name: OCL_ICD_VENDORS
          value: /etc/OpenCL/vendors
        - name: PCI_IDS_PATH
          value: /share/hwdata/pci.ids
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,video,utility
        - name: CANONICAL_URL
          value: http://localhost:13369
      # Ensure not to overlap other 'containerPort' values within this pod
      ports:
        - containerPort: 8181
          hostPort: 13369
          protocol: TCP
      workingDir: /
      volumeMounts:
        - mountPath: /conf
          name: config
  restartPolicy: unless-stopped
  volumes:
    - name: config
      hostPath:
        path: /home/kvineet/.config/beehive
        type: DirectoryOrCreate
