version: "3"
services:
  watchtower:
    command:
      - --cleanup
    environment:
      - TZ="Asia/Kolkata"
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    expose:
      - 8080/tcp
    image: docker.io/containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower: true
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - watchtower_default
    restart: unless-stopped
    volumes:
      - /home/kvineet/.config/docker/config.json:/config.json:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    working_dir: /
networks:
  watchtower_default:
    external: true
