apiVersion: v1
kind: Pod
metadata:
  labels:
    app: shoko
    io.containers.autoupdate: image
  name: shoko
spec:
  containers:
    # Create the first container: Dummy identd server on 113/TCP
    - name: shoko-server
      image: docker.io/shokoanime/server:latest
      env:
        - name: UID
          value: 1000
        - name: GID
          value: 1000
        - name: GIDLIST
          value: 1000
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: LANG
          value: en_US.UTF-8
        - name: HOME
          value: /tmp
        - name: AMDGPU_IDS
          value: /share/libdrm/amdgpu.ids
        - name: FONTCONFIG_PATH
          value: /etc/fonts
        - name: LD_LIBRARY_PATH
          value: /lib:/system
        - name: LIBVA_DRIVERS_PATH
          value: /lib/dri
        - name: OCL_ICD_VENDORS
          value: /etc/OpenCL/vendors
        - name: PCI_IDS_PATH
          value: /share/hwdata/pci.ids
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
      # Ensure not to overlap other 'containerPort' values within this pod
      ports:
        - containerPort: 8111
          hostPort: 13377
          protocol: TCP
      volumeMounts:
        - mountPath: /data/content
          name: content
        - mountPath: /data/import
          name: import
        - mountPath: /home/shoko/.shoko
          name: config
      workingDir: /home/shoko/
  restartPolicy: unless-stopped
  volumes:
    - name: content
      hostPath:
        path: /srv/webDav
        type: Directory
    - name: import
      hostPath:
        path: /home/kvineet/Downloads/torrents
        type: Directory
    - name: config
      hostPath:
        path: /media/Media/Shoko
        type: Directory
