apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webDav
  name: webDav
spec:
  containers:
    # Create the first container: Dummy identd server on 113/TCP
    - name: webDav-server
      image: docker.io/sashgorokhov/webdav
      env:
        - name: USERNAME
          value: kvineet
        - name: PASSWORD
          value: |
            ]H^R6Jbt*q>Mr{_o?Ez@3[xk{7EPBeVk*Dor
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ports:
        - containerPort: 80
          hostPort: 13388
          protocol: TCP
      volumeMounts:
        - mountPath: /media
          name: content
      workingDir: /
  restartPolicy: unless-stopped
  volumes:
    - name: content
      hostPath:
        path: /srv/webDav
        type: Directory
